project_id="kzjnkqeosrycfpxjwhil"


[server]
# The port on which the server will run
port = 8080

# CORS settings - Allow both local development and production URLs
cors = ["http://localhost:8080", "http://localhost:8081", "https://theset.live", "https://theset-verceledit.vercel.app"]

# Site URL configuration
site_url = "https://theset-verceledit.vercel.app"  # Production URL for Supabase dashboard

# Additional redirect URLs for authentication
additional_redirect_urls = [
  "http://localhost:8080/auth/callback",
  "http://localhost:8081/auth/callback",
  "https://theset-verceledit.vercel.app/auth/callback"
]

[database]
# Database connection settings
url="postgresql://postgres.kzjnkqeosrycfpxjwhil:Bambseth1590@aws-0-us-east-1.pooler.supabase.com:5432/postgres"

[auth]
# Authentication settings
jwt_secret="Pv1GTNBvpyJxe/tePxQv+3DYzg8gq/5o9prP+bmYq8YK2XKDdVREvCpVb4iBHFBgAM9goHKcAj7+s8cSS+lehg=="

# Enable local URL detection for development
# This allows the auth system to detect localhost URLs during development
# while still using the production URL in the Supabase dashboard
enable_local_url_detection = true

[api]
# API settings
enable = true

[auth.redirect_urls]
# Explicitly list all allowed redirect URLs
allow_list = [
  "http://localhost:8080",
  "http://localhost:8080/*",
  "http://localhost:8081",
  "http://localhost:8081/*",
  "https://theset-verceledit.vercel.app",
  "https://theset-verceledit.vercel.app/*",
  "https://theset.live",
  "https://theset.live/*"
]